version: '2'
services:  
  centos7-ssh:
    container_name: centos7-sshd
    network_mode: "bridge"
    image: centos:centos7-ssh
    ports:
      - "2122:22"
      - "8188:8080"
    mem_limit: 1024m
    privileged: true
    memswap_limit: -1
    volumes:
      - /data1/centos7-ssh:/data
      - /etc/timezone/timezone:/etc/timezone
    hostname: centos7-host
    restart: always
