version: '2'
services:  
  sshd.pub.corp:
    container_name: sshd.pub.corp
    network_mode: "bridge"
    image: centos:centos6-ssh
    ports:
      - "2122:22"
      - "8188:8080"
    mem_limit: 2048m
    privileged: true
    memswap_limit: -1
    volumes:
      - /data1/centos6-ssh:/data
      - /etc/timezone/timezone:/etc/timezone
    hostname: docker-centos6
    restart: always
